name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

      - name: Compile
        id: compile_linux
        uses: rust-build/rust-build.action@6febf1b0ed6499a46610b58ef9d810398e75f3c2 # v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          ARCHIVE_TYPES: tar.xz tar.gz
          UPLOAD_MODE: none

      - name: Compile
        id: compile_windows
        uses: rust-build/rust-build.action@6febf1b0ed6499a46610b58ef9d810398e75f3c2 # v1.4.5
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          ARCHIVE_TYPES: zip
          UPLOAD_MODE: none

      - name: Create Release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          makeLatest: true
          tag: ${{ steps.tag_version.outputs.new_tag || steps.tag_version.outputs.previous_tag }}
          name: ${{ steps.tag_version.outputs.new_tag || steps.tag_version.outputs.previous_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "\
            ${{ steps.compile_linux.outputs.BUILT_ARCHIVE }},\
            ${{ steps.compile_linux.outputs.BUILT_CHECKSUM }},\
            ${{ steps.compile_windows.outputs.BUILT_ARCHIVE }},\
            ${{ steps.compile_windows.outputs.BUILT_CHECKSUM }}"
