name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Compile
        id: compile_linux
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          ARCHIVE_TYPES: tar.xz
          UPLOAD_MODE: none

      - name: Compile
        id: compile_windows
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          ARCHIVE_TYPES: zip
          UPLOAD_MODE: none

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          writeToFile: false

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          artifacts: >-
            ${{ steps.compile_linux.outputs.BUILT_ARCHIVE }},
            ${{ steps.compile_linux.outputs.BUILT_CHECKSUM }},
            ${{ steps.compile_windows.outputs.BUILT_ARCHIVE }},
            ${{ steps.compile_windows.outputs.BUILT_CHECKSUM }},

